### PR TITLE
Adjust workflows for Hurricane branding

### PR DESCRIPTION
**Pull request by hasankayra04**
Closes https://github.com/GeyserMC/Hurricane/issues/14

### CODE REVIEW

**Comment by hasankayra04** [comment]
Bump.

**Comment by onebeastchris** [comment]
If we're gonna release a new release we might as well update the readme to show that the strider/pig riding workaround doesn't work on 1.20+

**Review by onebeastchris — APPROVED** [review]

**Comment by Konicai** [comment]
do the supported versions require an update?

**Comment by onebeastchris** [comment]
probs won't hurt too, yeah

**Comment by onebeastchris** [comment]
I just checked, 1.20.x isn't supported by Hurricane :/ 
No further version change should be needed then.

**Pull request merged**
